# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votations', '0010_auto_20180304_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votation',
            old_name='finished',
            new_name='active',
        ),
        migrations.AddField(
            model_name='votation',
            name='started',
            field=models.NullBooleanField(default=False),
        ),
    ]
